### ISSUE TITLE
bug: downloading private package tarball using axios fails

### ISSUE THREAD

**Issue by blimmer** [banyudu/npm-migrate-all#1]
The current logic to fetch a tarball using `axios` doesn't provide any authentication information. This causes the fetch of private packages to fail with a 401 error code. https://github.com/banyudu/npm-migrate-all/blob/b954ef6280a37e7b651976bc0445a661037ce69a/src/index.ts#L202-L207

Instead, you can use `npm pack` to fetch the tarball. This uses the authentication information provided by your NPM configuration.

```ts
const downloadTarball = async (
  pkgName: string,
  version: string,
  registry: string
) => {
  const { stdout } = await $`npm pack ${getRegistryParam(pkgName, registry)} --pack-destination=${tempDir} ${pkgName}@${version}`
  return fs.readFileSync(path.join(tempDir, stdout.trim()))
}
```

**Comment by banyudu** [comment]
Great, would you mind raising a PR for it?

**Comment by blimmer** [comment]
I'm a bit short on time, but I will do my best to open a PR. My intention with opening the issues was to at least provide documentation in case someone runs into these issues 👍
