### ISSUE TITLE
Workaround for publishConfig caveat?

### ISSUE THREAD

**Issue by ghost** [banyudu/npm-migrate-all#5]
Hey, my colleague @marcinbridge noticed that if you remove the logic related to patching publishConfig from this repo and instead pass the registry url through .npmrc, publishConfig doesn't override the registry and you don't need to patch publishConfig in the .tgz - so the SHAs remain unchanged despite publishConfig existing

Relevant parts in npm cli:
https://github.com/npm/cli/blob/004cf40bec94649451acde82a33d619947b2c00c/lib/commands/publish.js#L100

The fn impl that the above link shows:
https://github.com/npm/npm-registry-fetch/blob/main/lib/index.js#L199-L201

So the point seems to be to have the "!registry" condition NOT trigger in the above fn, and then registry URL that we want to migrate to will be taken from the opts (.npmrc), rather than from publishConfig
![Untitled](https://github.com/banyudu/npm-migrate-all/assets/5359825/620f732f-6f92-4115-bdef-53f2da8b1fc4)

EDIT: Ah sorry, seems like this only works for packages that are scoped, that is if the .npmrc has a set registry for a certain scope. Still, I think many companies have internal repos with just scoped pkgs?

**Comment by banyudu** [comment]
It's worth a try, thanks! I may try it over the weekend, PR is welcome too!

**Comment by banyudu** [comment]
Published in  [npm-migrate-all@0.3.0](https://www.npmjs.com/package/npm-migrate-all/v/0.3.0)
